query UserInfo {
  users(limit: 1) {
    id
    name
    firstname
    emails {
      email
    }
    features: user_feature_maps {
      feature {
        name
        id
        product_id
      }
    }
    get_started_viewed
    groups: user_groups(where: { _not: { is_deleted: { _eq: true } } }) {
      id: group_id
      group {
        name
        group_id
      }
    }
    username
    roles {
      role {
        description
        id
        name
      }
    }
    accepted_tos
    accepted_tos_time
    survey_submitted_time
  }
  features(where: { public: { _eq: true } }) {
    id
    name
  }
}
