# # LIMITATIONS ON EXTERNAL USE: external users are only allowed to depend
# # on certain fields exposed in this query. No backwards compatibility
# # guarantees are made for the fields marked "DISALLOWED".
#
# external_query = true
# roles = ["default"]

query UserInfo {
  users(limit: 1) {
    id
    name
    firstname
    emails {
      email
    }
    # DISALLOWED: .features is disallowed for external users
    # No guarantees are made about the contents or validity of this field.
    features: user_feature_maps {
      feature {
        name
        id
        product_id
      }
    }
    # DISALLOWED: .get_started_viewed is disallowed for external users
    # No guarantees are made about the contents or validity of this field.
    get_started_viewed
    groups: user_groups(where: { _not: { is_deleted: { _eq: true } } }) {
      id: group_id
      group {
        name
        group_id
      }
    }
    username
    roles {
      role {
        description
        id
        name
      }
    }
    accepted_tos
    # DISALLOWED: .accepted_tos_time is disallowed for external users
    # No guarantees are made about the contents or validity of this field.
    accepted_tos_time
    survey_submitted_time
  }
  # DISALLOWED: .features is disallowed for external users
  # No guarantees are made about the contents or validity of this field.
  features(where: { public: { _eq: true } }) {
    id
    name
  }
}
